nodejs/create-node-meeting-artifacts

- create-node-meeting-artifacts.js
- package.json
Pull the meeting group for argv.
Fixes: https://github.com/mhdawson/create-node-meeting-artifacts/issues/2
> remove hard coding of meeting group.

- templates/observers_commcomm
Adam's become a CommComm member and no longer needs to be included in the observers list because he's become a member. Ref: https://github.com/nodejs/community-committee/pull/265
> Remove Adam Miller (CommComm Member)

- TEMPLATES_DOCUMENTATION.md
Updates the templates documentation with a quick note about *where* things should go. Stems from a discussion with a CommComm observer who wasn't sure about this, and assumed they needed to go inside the respective repo.
> Add note about where templates should go

- templates/minutes_base_commcomm
- templates/observers_commcomm
Remove Tiriel from CommComm Observers, add attendance note to CommCommMinutes
> Attendance note for CommComm & removing Tiriel

- templates/invited_Release
[nodejs/release team](https://github.com/orgs/nodejs/teams/release) is lower case.
> Fix casing of release team

- templates/invited_tsc
Ref: https://github.com/nodejs/node/pull/27633
> remove Rod Vagg from invited TSC list

- templates/observers_tsc
Sam is now on the TSC invited list.
Refs: https://github.com/nodejs/create-node-meeting-artifacts/pull/61
> remove Sam Roberts from TSC observers list

- templates/meeting_base_diag
Recurring Zoom links stay the same except if the meeting is not started for 365 days.
Unfortunately, Zoom doesn't support meeting aliases for nonpersonal meetings.
> feat: add zoom link

- templates/minutes_base_commcomm
- templates/minutes_base_tsc
Instead of having permanently open issues just so the tooling can add
stuff to the agenda, include permanent standing issues in the templates.
While we're at it, get rid of "Q&A, Other" from TSC meeting because we
don't do Q&A anymore and "Other" seems lose-able.
Closes: https://github.com/nodejs/admin/issues/395
Closes: https://github.com/nodejs/TSC/issues/423
> Update meeting templates for standing issues

- templates/minutes_base_cross_project_council
- templates/minutes_base_standards
Updating the calendar link in the footer of meetings notes to point to the OpenJS calendar rather than the Node.js calendar.
> doc: updating calendar link for openjsf meetings

- templates/meeting_base_commcomm
New url as last one had expired.
> update link for meeting in commcomm template

- templates/meeting_base_wrsi
Updated the zoom link for WRSI, the old link was not from the Node js Com Com account now it is fixed
> Updated Zoom link

- TEMPLATES_DOCUMENTATION.md
- templates/invited_loaders
- templates/meeting_base_loaders
- templates/minutes_base_loaders
Add templates for the new Loaders team.
I’ll probably need another PR later for a new Zoom link but hopefully we can use this one for now.
> templates: loaders team

- templates/meeting_base_tsc
I don't have statistics to back it up, but I don't believe the statement that "many of us will be available on IRC during the meeting" is still true. We also don't typically bring up questions from IRC during meetings, so the statement is inaccurate and could lead the live meeting audience to ask questions in the wrong place. Therefore removing it seems like a good idea.
> remove irc mention from TSC meeting template

- templates/minutes_base_cross_project_council
This will help us to stay ahead of elections and other important dates and reminders.
> Add Dates and Reminders to CPC meeting template

- TEMPLATES_DOCUMENTATION.md
- create-node-meeting-artifacts.js
- templates/meeting_base_cross_project_council
Allows adding an optional label to the generated GitHub issue itself.
Adds the `cpc-meeting` label to Cross Project Council meetings.
> Allow adding a label to the generated GitHub issue itself

- templates/meeting_base_performance
To live stream, we need to change Performance Team meetings to a webinar. This pull request changes the link.
Fixes: https://github.com/nodejs/performance/issues/42
cc @mhdawson
> fix: change performance meetings to webinar on zoom

- templates/invited_tsc
We'll probably want to add everyone on the regular member list back in, but let's do that in a separate PR.
> Remove fhinkel from meeting list

- templates/meeting_base_build
For consistency with other meetings, add the section explaining the emoji's to react with to indicate whether invitees are intending to attend the meeting to the build meeting issues.
cc @nodejs/build
> Add emoji legend to build meeting issues

- templates/meeting_base_security_collab
Updates the meeting zoom link to an OpenJS meeting so that we can live stream.
> Update zoom link in meeting_base_security_collab

- templates/meeting_base_cross_project_council
There is a different zoom link for the two different times that the CPC meets to it seems easiest to simply point to the calendar for the most up to date and accurate link for each meeting.
> updating CPC zoom link to point to calendar

- templates/meeting_base_Release
- templates/meeting_base_benchmarking
- templates/meeting_base_build
- templates/meeting_base_commcomm
- templates/meeting_base_cross_project_council
- templates/meeting_base_diag
- templates/meeting_base_diag_deepdive
- templates/meeting_base_loaders
- templates/meeting_base_michael
- templates/meeting_base_modules
- templates/meeting_base_next-10
- templates/meeting_base_outreach
- templates/meeting_base_package-maintenance
- templates/meeting_base_security-wg
- templates/meeting_base_tooling
- templates/meeting_base_typescript
- templates/meeting_base_userfeedback
- templates/meeting_base_uvwasi
- templates/meeting_base_web-server-frameworks
We lost the original calendar, possibly because of google gmail cleanup. Use new calendar link provided by foundation.
> doc: update calendar link for all meetings
