nodejs/create-node-meeting-artifacts

- bin/create-meeting
- package.json
`npm run release-meeting` to create Release meeting.
`npm run all` to create meeting for TSC, Benchmark and Release Group.
> package.json: add release support and all for all the meeting

- templates/observers_tsc
https://github.com/nodejs/TSC/issues/485
cc @TimothyGu
> Add @TimothyGu as a TSC observer

- templates/observers_commcomm
ref: https://github.com/nodejs/community-committee/issues/254
> Remove Toby Farley

- templates/observers_commcomm
Since he became a full member.
> Remove @amiller-gh from CommComm observers list (full member)

- templates/observers_commcomm
Ref: nodejs/community-committee#281
> Add @elainechan as CommComm observer.

- templates/minutes_base_userfeedback
> minutes_base_userfeedback

- templates/meeting_base_userfeedback
> meeting_base_userfeedback

- templates/invited_userfeedback
- templates/meeting_base_userfeedback
- templates/minutes_base_userfeedback
Updates to user feedback creation (WIP)
> User Feedback Updates

- templates/observers_commcomm
Adds Patricia Realini as a CommComm observer.
> Add Patricia Realini to CommComm Observers

- templates/meeting_base_tsc
As per https://github.com/nodejs/TSC/issues/612#issuecomment-429973210, proposing this draft version.
cc @Trott @mhdawson
> include meaning of emojis in TSC meeting base

- templates/invited_tooling
- templates/meeting_base_tooling
- templates/minutes_base_tooling
@mhdawson 	I've added the templates, but don't have a Zoom link.  What should I put there?
> add templates for tooling group

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/650
cc @Trott
> Add back Rich Trott to TSC invitation list

- templates/invited_tsc
James has moved to Emeritus for the time being to focus on internal business for his employer.
> remove jasnell from invite list

- templates/minutes_base_package-maintenance
About to add Package Maintenance Project Board review question to Agenda.
> Maybe monad of Project Board Review

- templates/invited_tsc
Ali is taking a break from TSC.
> remove Ali from TSC invitation list

- templates/observers_tsc
Refs: https://github.com/nodejs/TSC/issues/687
> doc: add Sam Roberts as observer for TSC

- templates/invited_outreach
- templates/meeting_base_outreach
- templates/minutes_base_outreach
- templates/observers_outreach
Closes https://github.com/nodejs/outreach/issues/6
> feat: Add Outreach WG Meeting.

- templates/invited_tsc
Ref: https://github.com/nodejs/node/pull/27606
Ref: https://github.com/nodejs/TSC/issues/687
> added Sam Roberts to TSC invited list

- templates/invited_nodejsafrica_leadership
- templates/invited_nodejsafrica_members
- templates/meeting_base_nodejsafrica
Create Meeting Africa for Nodejs Africa community cc @mhdawson
> added Nodejs Africa Meetings

- templates/meeting_base_commcomm
Discussed in CommComm meeting 27-06-2019
> Add reactions to help invitees RSVP

- templates/meeting_base_wrsi
* Add reactions to help WRSI invitees RSVP
* Include link to past meeting recordings
> Update WRSI meeting base

- templates/meeting_base_wrsi
ref: https://github.com/nodejs/website-redesign/issues/147
> chore: Move website-redesign repo to nodejs.dev.

- templates/invited_standards
- templates/meeting_base_standards
- templates/minutes_base_standards
Would be good to generate meetings for standards team
Meets every other Tuesday. Need to get added to cal.
> add standards

- templates/observers_tsc
Refs: https://github.com/nodejs/TSC/issues/747#issuecomment-522577395
cc @tniessen @cclauss
> Add @cclauss and @tniessen to TSC observers

- templates/minutes_base_commcomm
Capturing our process in the agenda so everyone can follow.
> Update agenda, add section for initiative updates

- templates/observers_tsc
Refs: https://github.com/nodejs/TSC/issues/811
Refs: https://github.com/nodejs/TSC/pull/814
> template: add Ruben Bridgewater to TSC observers

- templates/invited_tsc
- templates/observers_tsc
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: add Ruben to TSC

- templates/meeting_base_wrsi
This replaces the old zoom link with https://zoom.us/j/230136002
/cc @nodejs/website-redesign
> doc: Update WRSI Zoom link

- templates/meeting_base_standards
> The Standards team is now officially a Working Group

- templates/invited_tsc
/ping @sam-github 
Fast-track?
> remove Sam Roberts from tsc template

- templates/invited_wrsi
> fix: website-redesign to nodejs-dev team

- templates/invited_tsc
> remove addaleax from TSC template

- templates/invited_performance
- templates/meeting_base_performance
- templates/minutes_base_performance
I'm not quite for about CALENDAR_ID and zoom link for the meetings.
> add templates for performance team

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/1308
Signed-off-by: Michael Dawson <mdawson@devrus.com>
> doc: add Rafael to invited tsc list

- templates/invited_next-10
> doc: fix missed space

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/1364
> add MoLow to the TSC

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/1388
> doc: add Ruy

- templates/minutes_base_next-10
there missing space for dot list.
> fix: missing space

- templates/invited_tsc
Refs:  https://github.com/nodejs/TSC/issues/1463
> Move Rich to non-voting

- templates/minutes_base_cross_project_council
> Update CPC meeting doc template

- templates/meeting_base_security-wg
> doc: add emoji for attendees

- templates/invited_tsc
Refs: https://github.com/nodejs/node/pull/51411
> Remove RaisinTen from the list of invitees

- templates/invited_tsc
We agreed to invite Joe to the TSC meetings to help cover CPC updates -
Refs: https://github.com/nodejs/TSC/pull/1512
> Update invited_tsc - Add Joe

- templates/invited_tsc
Refs: https://github.com/nodejs/node/pull/52457
> Remove ChALkeR from invited_tsc

- templates/invited_ecosystem_report
- templates/meeting_base_ecosystem_report
- templates/minutes_base_ecosystem_report
Adding the OpenJS foundation ecosystem report collab space meetings
> Adding the ecosystem report collab space

- templates/invited_tsc
Change Yagiz from voting to regular TSC member
@nodejs/tsc 
Refs: https://github.com/nodejs/node/pull/52932#event-12777028672
> Offboard Yagiz 

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/1550
> Add Marco Ippolito to voting TSC

- templates/invited_tsc
Refs: https://github.com/nodejs/node/pull/53599
> Remove Myles from invited_tsc

- templates/invited_tsc
Refs: https://github.com/nodejs/node/pull/53693
> Remove Danielle from invited_tsc

- templates/invited_tsc
> change invited_tsc to reflect membership change

- templates/invited_typescript
- templates/meeting_base_typescript
- templates/minutes_base_typescript
Should I create the recurring meeting on zoom? how do it work?
> chore: add typescript team to calendar

- templates/invited_tsc
Refs: https://github.com/nodejs/TSC/issues/1643#issuecomment-2444870565
> fix: correct Joe's @-mention in invited_tsc

- templates/invited_tsc
Refs: https://github.com/nodejs/node/pull/56580
> remove apapirovski from `invited_tsc`

- package.json
- templates/invited_web
- templates/meeting_base_web
- templates/minutes_base_web
> feat(meetings): add web
